#!/usr/bin/env python3
"""Install a check-only pre-commit MissionCenter hook without touching post-commit."""
from __future__ import annotations
import sys
from pathlib import Path

TOOL_MARKER = "# Auto-generated by Codex Mission Center Git Hook Installer"
PRE_COMMIT_HOOK_SCRIPT = f'''#!/bin/sh
{TOOL_MARKER}
REPO_ROOT=$(git rev-parse --show-toplevel)
PYTHONUTF8=1
export PYTHONUTF8
PY_ARGS=""
if command -v python3 >/dev/null 2>&1 && python3 -c 'import sys; raise SystemExit(0 if sys.version_info[0] == 3 else 1)' >/dev/null 2>&1; then
  PYTHON=python3
elif command -v python >/dev/null 2>&1 && python -c 'import sys; raise SystemExit(0 if sys.version_info[0] == 3 else 1)' >/dev/null 2>&1; then
  PYTHON=python
elif command -v py >/dev/null 2>&1 && py -3 -c 'import sys; raise SystemExit(0 if sys.version_info[0] == 3 else 1)' >/dev/null 2>&1; then
  PYTHON=py
  PY_ARGS="-3"
else
  echo "[MissionCenter] Python 3 interpreter not found; commit blocked." >&2
  exit 1
fi
"$PYTHON" $PY_ARGS "$REPO_ROOT/scripts/check_mission_center.py" "$REPO_ROOT"
'''
# Compatibility name for callers that imported the old constant; it is intentionally empty.
POST_COMMIT_HOOK_SCRIPT = ""

def install_git_hook(target_repo: Path = Path('.')) -> bool:
    git_dir=target_repo.resolve()/'.git'
    if not git_dir.is_dir(): print(f"[MissionCenter] Warning: {target_repo} is not a Git repository root with a .git directory."); return False
    hooks=git_dir/'hooks'; hooks.mkdir(parents=True,exist_ok=True); hook=hooks/'pre-commit'
    if hook.exists():
        raw=hook.read_bytes()
        if raw == PRE_COMMIT_HOOK_SCRIPT.encode('utf-8'): print(f"[MissionCenter] Pre-commit Git Hook is already installed at {hook}."); return True
        try: existing=raw.decode('utf-8')
        except UnicodeDecodeError: existing=''
        if TOOL_MARKER not in existing: print(f"[MissionCenter] Refusing to overwrite existing non-Mission-Center hook: {hook}"); return False
    hook.write_bytes(PRE_COMMIT_HOOK_SCRIPT.encode('utf-8'))
    if sys.platform != 'win32': hook.chmod(0o755)
    print(f"[MissionCenter] Check-only pre-commit Git Hook installed to {hook}!"); return True

if __name__ == '__main__': raise SystemExit(0 if install_git_hook(Path(sys.argv[1]) if len(sys.argv)>1 else Path('.')) else 1)
