<#
.SYNOPSIS
    Installs a post-commit Git hook to automatically sync Mission Center on commit.
#>

[CmdletBinding()]
param(
    [string]$TargetRepoPath = "."
)

$ErrorActionPreference = 'Stop'
$GitDir = Join-Path (Resolve-Path $TargetRepoPath) ".git"

if (-not (Test-Path $GitDir)) {
    throw "Target path '$TargetRepoPath' is not a Git repository root (.git not found)."
}

$HooksDir = Join-Path $GitDir "hooks"
if (-not (Test-Path $HooksDir)) {
    New-Item -ItemType Directory -Path $HooksDir -Force | Out-Null
}

$PostCommitFile = Join-Path $HooksDir "post-commit"
$HookContent = "#!/bin/sh`n# Auto-generated by Codex Mission Center Git Hook Installer`nREPO_ROOT=`$(git rev-parse --show-toplevel)`npython `"`$REPO_ROOT/skills/mission-center/scripts/sync_mission_center.py`"`npython `"`$REPO_ROOT/skills/mission-center/scripts/normalize_mission_center.py`"`n"

if (Test-Path -LiteralPath $PostCommitFile) {
    $existingHook = [System.IO.File]::ReadAllText($PostCommitFile)
    $toolMarker = '# Auto-generated by Codex Mission Center Git Hook Installer'
    if ($existingHook -notmatch [regex]::Escape($toolMarker)) {
        throw "Refusing to overwrite existing non-Mission-Center post-commit hook: $PostCommitFile"
    }

    if ($existingHook -eq $HookContent) {
        Write-Host "[MissionCenter] Post-commit Git Hook is already installed at: $PostCommitFile" -ForegroundColor Yellow
        exit 0
    }
}

# Use WriteAllText to avoid BOM
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($PostCommitFile, $HookContent, $utf8NoBom)
Write-Host "[MissionCenter] Post-commit Git Hook installed to: $PostCommitFile" -ForegroundColor Green
