<#
.SYNOPSIS
    Installs a post-commit Git hook to automatically sync Mission Center on commit.
#>

[CmdletBinding()]
param(
    [string]$TargetRepoPath = "."
)

$ErrorActionPreference = 'Stop'
$GitDir = Join-Path (Resolve-Path $TargetRepoPath) ".git"

if (-not (Test-Path $GitDir)) {
    Write-Warning "Target path '$TargetRepoPath' is not a Git repository root (.git not found)."
    exit 0
}

$HooksDir = Join-Path $GitDir "hooks"
if (-not (Test-Path $HooksDir)) {
    New-Item -ItemType Directory -Path $HooksDir -Force | Out-Null
}

$PostCommitFile = Join-Path $HooksDir "post-commit"
$HookContent = "#!/bin/sh`n# Auto-generated by Codex Mission Center Git Hook Installer`nREPO_ROOT=`$(git rev-parse --show-toplevel)`npython3 `"`$REPO_ROOT/skills/mission-center/scripts/sync_mission_center.py`" 2>/dev/null || true`npython3 `"`$REPO_ROOT/skills/mission-center/scripts/normalize_mission_center.py`" 2>/dev/null || true`n"

# Use WriteAllText to avoid BOM (PS5.1 Set-Content -Encoding UTF8 adds BOM)
[System.IO.File]::WriteAllText($PostCommitFile, $HookContent, [System.Text.Encoding]::UTF8)
Write-Host "[MissionCenter] Post-commit Git Hook installed to: $PostCommitFile" -ForegroundColor Green
