#!/usr/bin/env python3
"""
Git Hook Installer for Codex Mission Center.
Installs a post-commit hook in .git/hooks/ to auto-sync MissionCenter on git commit.
"""

import os
import sys
from pathlib import Path

POST_COMMIT_HOOK_SCRIPT = """#!/bin/sh
# Auto-generated by Codex Mission Center Git Hook Installer
REPO_ROOT=$(git rev-parse --show-toplevel)
python3 "$REPO_ROOT/skills/mission-center/scripts/sync_mission_center.py" 2>/dev/null || true
python3 "$REPO_ROOT/skills/mission-center/scripts/normalize_mission_center.py" 2>/dev/null || true
"""

def install_git_hook(target_repo: Path = Path('.')):
    git_dir = target_repo.resolve() / ".git"
    if not git_dir.exists():
        print(f"[MissionCenter] Warning: {target_repo} is not a Git repository root (.git not found).")
        return False

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    hook_file = hooks_dir / "post-commit"
    hook_file.write_text(POST_COMMIT_HOOK_SCRIPT, encoding="utf-8")

    # Make executable on Unix
    if sys.platform != "win32":
        hook_file.chmod(0o755)

    print(f"[MissionCenter] Post-commit Git Hook successfully installed to {hook_file}!")
    return True

if __name__ == "__main__":
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else Path('.')
    install_git_hook(target)
