<# Installs the same check-only pre-commit hook as install_git_hook.py. #>
[CmdletBinding()] param([string]$TargetRepoPath = ".")
$ErrorActionPreference = 'Stop'
$repo = (Resolve-Path $TargetRepoPath).Path
$gitDir = Join-Path $repo '.git'
if (-not (Test-Path $gitDir)) { throw "Target path '$TargetRepoPath' is not a Git repository root (.git not found)." }
$hooks = Join-Path $gitDir 'hooks'; New-Item -ItemType Directory -Force -Path $hooks | Out-Null
$hook = Join-Path $hooks 'pre-commit'; $marker = '# Auto-generated by Codex Mission Center Git Hook Installer'
$content = "#!/bin/sh`n$marker`nREPO_ROOT=`$(git rev-parse --show-toplevel)`npython3 `"`$REPO_ROOT/scripts/check_mission_center.py`" `"`$REPO_ROOT`"`n"
if (Test-Path -LiteralPath $hook) { $old=[IO.File]::ReadAllText($hook); if ($old -notmatch [regex]::Escape($marker)) { throw "Refusing to overwrite existing non-Mission-Center hook: $hook" }; if ($old -eq $content) { Write-Host '[MissionCenter] Pre-commit Git Hook is already installed.'; exit 0 } }
[IO.File]::WriteAllText($hook,$content,(New-Object Text.UTF8Encoding($false)))
Write-Host "[MissionCenter] Check-only pre-commit Git Hook installed to: $hook"
